package govite

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"reflect"
	"strings"
)

type PropsTypeGenerator struct {
	propsTypes []reflect.Type
}

func NewPropsTypeGenerator() *PropsTypeGenerator {
	return &PropsTypeGenerator{
		propsTypes: make([]reflect.Type, 0),
	}
}

type propsTypeGeneratorContextKey struct{}

func WithPropsTypeGenerator(ctx context.Context, generator *PropsTypeGenerator) context.Context {
	return context.WithValue(ctx, propsTypeGeneratorContextKey{}, generator)
}

func PropsTypeGeneratorFromContext(ctx context.Context) (*PropsTypeGenerator, error) {
	value := ctx.Value(propsTypeGeneratorContextKey{})
	if value == nil {
		return nil, errors.New("props type generator not found in context")
	}
	generator, ok := value.(*PropsTypeGenerator)
	if !ok {
		return nil, errors.New("invalid props type generator type in context")
	}
	return generator, nil
}

func (g *PropsTypeGenerator) RegisterPropsType(rt reflect.Type) {
	g.propsTypes = append(g.propsTypes, rt)
}

func (g *PropsTypeGenerator) GenerateTypeScriptPropsTypes() error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by govite. DO NOT EDIT.\n\n")

	generatedTypes := make(map[reflect.Type]bool)
	var typeDefinitions []string

	var processType func(t reflect.Type) string
	processType = func(t reflect.Type) string {
		for t.Kind() == reflect.Ptr {
			t = t.Elem()
		}

		switch t.Kind() {
		case reflect.String:
			return "string"
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Float32, reflect.Float64:
			return "number"
		case reflect.Bool:
			return "boolean"
		case reflect.Slice, reflect.Array:
			return processType(t.Elem()) + "[]"
		case reflect.Map:
			keyType := processType(t.Key())
			valueType := processType(t.Elem())
			return "{ [key: " + keyType + "]: " + valueType + " }"
		case reflect.Struct:
			if t.PkgPath() == "time" && t.Name() == "Time" {
				return "string"
			}

			typeName := t.Name()
			if typeName == "" {
				// Anonymous struct
				var s bytes.Buffer
				s.WriteString("{\n")
				for i := range t.NumField() {
					field := t.Field(i)
					if !field.IsExported() {
						continue
					}
					tag := field.Tag.Get("json")
					fieldName := field.Name
					if tag != "" && tag != "-" {
						parts := strings.Split(tag, ",")
						fieldName = parts[0]
					}
					s.WriteString(fmt.Sprintf("  %s: %s;\n", fieldName, processType(field.Type)))
				}
				s.WriteString("}")
				return s.String()
			}

			if !generatedTypes[t] {
				generatedTypes[t] = true
				var s bytes.Buffer
				s.WriteString(fmt.Sprintf("export type %s = {\n", typeName))
				for i := range t.NumField() {
					field := t.Field(i)
					if !field.IsExported() {
						continue
					}
					tag := field.Tag.Get("json")
					fieldName := field.Name
					if tag != "" && tag != "-" {
						parts := strings.Split(tag, ",")
						fieldName = parts[0]
					}
					s.WriteString(fmt.Sprintf("  %s: %s;\n", fieldName, processType(field.Type)))
				}
				s.WriteString("}\n")
				typeDefinitions = append(typeDefinitions, s.String())
			}
			return typeName
		case reflect.Interface:
			return "any"
		default:
			return "any"
		}
	}

	for _, rt := range g.propsTypes {
		processType(rt)
	}

	for i := len(typeDefinitions) - 1; i >= 0; i-- {
		buf.WriteString(typeDefinitions[i])
		buf.WriteString("\n")
	}

	return os.WriteFile("types.gen.ts", buf.Bytes(), os.ModePerm)
}
