// Code generated by govite. DO NOT EDIT.

export type AppProps = {
}

export type IndexProps = {
  name: string;
  age: number;
  isActive: boolean;
  score: number;
  address: Address;
  tags: Tag[];
  metadata: { [key: string]: string };
  createdAt: string;
  website: string;
}

export type Tag = {
  name: string;
  color: string;
}

export type Address = {
  street: string;
  city: string;
  zipCode: string;
}

