// Code generated by govite. DO NOT EDIT.

export type UsersProps = {
  users: User[];
  currentPage: number;
  totalPages: number;
  totalUsers: number;
  pageSize: number;
}

export type User = {
  id: number;
  name: string;
  email: string;
  role: string;
  status: string;
  joinedAt: string;
}

export type IndexProps = {
  name: string;
  age: number;
  isActive: boolean;
  score: number;
  address: Address;
  tags: Tag[];
  metadata: { [key: string]: string };
  createdAt: string;
  website: string;
}

export type Tag = {
  name: string;
  color: string;
}

export type Address = {
  street: string;
  city: string;
  zipCode: string;
}

